[versions]
agp = "8.2.0-alpha08"
androidx-annotation = "1.6.0"
google-material = "1.9.0"
androidx-preference = "1.2.0"
gradle = "8.2.0-alpha08"
desugar_jdk_libs_nio = "2.0.3"
junit = "4.13.2"
androidx-test-ext-junit = "1.1.5"
espresso-core = "3.5.1"
multidex = "2.0.1"
annotation = "1.2.0"
preference = "1.1.0"
material = "1.5.0"

[libraries]
androidx-annotation-1_6_0 = { module = "androidx.annotation:annotation", version.ref = "androidx-annotation" }
androidx-multidex = { module = "androidx.multidex:multidex", version.ref = "multidex" }
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
androidx-preference = { module = "androidx.preference:preference", version.ref = "preference" }
androidx-preference-1_2_0 = { module = "androidx.preference:preference", version.ref = "androidx-preference" }
material = { module = "com.google.android.material:material", version.ref = "material" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
desugar_jdk_libs_nio = { module = "com.android.tools:desugar_jdk_libs_nio", version.ref = "desugar_jdk_libs_nio" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
material-1_9_0 = { module = "com.google.android.material:material", version.ref = "google-material" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }

[bundles]

